name: Publish to NuGet

on:
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore src/Polyrific.Security.CookiePolicy
    - name: Build
      run: dotnet build -c Release --no-restore src/Polyrific.Security.CookiePolicy
    - name: Pack
      run: dotnet pack -c Release --no-build --include-symbols --include-source -p:PackageVersion=$GITHUB_REF -o nupkg src/Polyrific.Security.CookiePolicy
    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --skip-duplicate --api-key $NUGET_TOKEN
